// pr.cjs
const { execSync } = require('child_process');
const { gitHash, gitBranch } = require('./utils.cjs');
const { isArm64 } = require('./config.cjs');

function generatePRComment(results) {
  const { regressions, improvements, benchmarks, perfScore } = results;

  let comment = `## 📊 Benchmark Results\n\n`;
  comment += `**Commit:** \`${gitHash()}\`\n`;
  comment += `**Branch:** ${gitBranch()}\n`;
  comment += `**Platform:** ${isArm64 ? 'ARM64 (Snapdragon 680)' : 'x86_64'}\n\n`;

  if (perfScore !== 'N/A') {
    comment += `### 🎯 Performance Score: **${perfScore}**/100\n\n`;
  }

  if (regressions.length > 0) {
    comment += `### 🔴 Regressions (${regressions.length})\n\n`;
    comment += `| Benchmark | Current | Baseline | Change |\n`;
    comment += `|-----------|---------|----------|--------|\n`;
    for (const r of regressions) {
      comment += `| ${r.name} | ${r.current.toFixed(0)} | ${r.baseline.toFixed(0)} | ${r.change.toFixed(1)}% |\n`;
    }
    comment += `\n⚠️ **Action Required:** These benchmarks regressed. Consider investigating.\n\n`;
  } else {
    comment += `### ✅ No Regressions Detected\n\n`;
  }

  if (improvements.length > 0) {
    comment += `### 🟢 Improvements (${improvements.length})\n\n`;
    comment += `| Benchmark | Current | Baseline | Change |\n`;
    comment += `|-----------|---------|----------|--------|\n`;
    for (const i of improvements.slice(0, 10)) {
      comment += `| ${i.name} | ${i.current.toFixed(0)} | ${i.baseline.toFixed(0)} | +${i.change.toFixed(1)}% |\n`;
    }
    if (improvements.length > 10) {
      comment += `\n_...and ${improvements.length - 10} more improvements_\n`;
    }
    comment += `\n`;
  }

  comment += `---\n\n`;
  comment += `*🤖 Generated by yuyu-bench*\n`;

  return comment;
}

async function postPRComment(comment) {
  if (process.env.GITHUB_TOKEN && process.env.GITHUB_PR_NUMBER) {
    try {
      const payload = {
        body: comment,
        issue_number: parseInt(process.env.GITHUB_PR_NUMBER),
        owner: process.env.GITHUB_REPO_OWNER || 'Liveiciee',
        repo: process.env.GITHUB_REPO_NAME || 'yuyucode'
      };

      const url = `https://api.github.com/repos/${payload.owner}/${payload.repo}/issues/${payload.issue_number}/comments`;

      execSync(`curl -X POST "${url}" \
        -H "Authorization: token ${process.env.GITHUB_TOKEN}" \
        -H "Content-Type: application/json" \
        -d '${JSON.stringify({ body: comment })}'`, {
        cwd: process.cwd(),
        encoding: 'utf8'
      });

      console.log('💬 PR comment posted successfully');
    } catch (err) {
      console.log('⚠️ Failed to post PR comment:', err.message);
    }
  }
}

module.exports = { generatePRComment, postPRComment };
