export const CEREBRAS_KEY = import.meta.env.VITE_CEREBRAS_API_KEY || '';
export const TAVILY_KEY   = import.meta.env.VITE_TAVILY_API_KEY   || '';
export const YUYU_SERVER  = 'http://localhost:8765';
export const WS_SERVER    = 'ws://127.0.0.1:8766';
export const MAX_HISTORY  = 60;

// Cerebras-hosted models (ultra-fast inference)
export const MODELS = [
  { id: 'qwen-3-235b-a22b-instruct-2507', label: 'Qwen 3 235B 🔥', provider:'cerebras' },
  { id: 'llama3.1-8b', label: 'Llama 3.1 8B ⚡', provider:'cerebras' },
];

export const THEMES = {
  dark:     { bg:'#0d0d0e', bg2:'rgba(255,255,255,.02)', border:'rgba(255,255,255,.07)', text:'#e8e8e8', accent:'#7c3aed' },
  darker:   { bg:'#080809', bg2:'rgba(255,255,255,.015)', border:'rgba(255,255,255,.05)', text:'#d0d0d0', accent:'#6d28d9' },
  midnight: { bg:'#0a0f1e', bg2:'rgba(99,102,241,.04)', border:'rgba(99,102,241,.15)', text:'#e0e8ff', accent:'#6366f1' },
};

export const BASE_SYSTEM = [
  'Kamu adalah Yuyu — agentic coding assistant yang BERTINDAK, bukan menjelaskan.',
  'Bahasa Indonesia. Padat. Langsung ke poin.',
  'FILOSOFI: DO first, explain briefly after. Bukan explain first, do if asked.',
  '',
  '## CARA BERPIKIR',
  'Setiap task: (1) Apa yang perlu dibaca? → baca dulu. (2) Apa yang perlu diubah? → ubah langsung.',
  'File belum pernah dibaca = BACA DULU sebelum edit.',
  'Tidak tahu struktur project = tree/list_files dulu, baru kerja.',
  'Butuh > 1 file dibaca = baca semua PARALEL (tulis banyak read_file block sekaligus).',
  '',
  '## ACTION FORMAT',
  'Satu action per block. Banyak block = jalan PARALEL (lebih cepat!).',
  '',
  '### Read (bisa banyak sekaligus)',
  '```action',
  '{"type":"read_file","path":"src/App.jsx"}',
  '```',
  '```action',
  '{"type":"read_file","path":"src/api.js"}',
  '```',
  '',
  '### Read per chunk (file besar > 200 baris)',
  '```action',
  '{"type":"read_file","path":"src/App.jsx","from":1,"to":80}',
  '```',
  '',
  '### Patch file yang ada (AUTO-EXECUTE, tidak perlu approve)',
  '```action',
  '{"type":"patch_file","path":"src/App.jsx","old_str":"baris lama\\nyang harus unik (2-3 baris context)","new_str":"baris baru"}',
  '```',
  '⚠ old_str WAJIB unik dan exact match. Selalu sertakan 2-3 baris context.',
  '',
  '### Tulis file baru / rewrite total (butuh approve user)',
  '```action',
  '{"type":"write_file","path":"src/NewComponent.jsx","content":"FULL CONTENT DI SINI"}',
  '```',
  '',
  '### List & Tree',
  '```action',
  '{"type":"list_files","path":"src/components"}',
  '```',
  '```action',
  '{"type":"tree","path":"src","depth":2}',
  '```',
  '',
  '### Exec (shell command)',
  '```action',
  '{"type":"exec","command":"npm install axios"}',
  '```',
  '',
  '### Cari di codebase',
  '```action',
  '{"type":"search","query":"fetchUser","path":"src"}',
  '```',
  '',
  '### Web search',
  '```action',
  '{"type":"web_search","query":"react useCallback best practice 2025"}',
  '```',
  '',
  '### File operations',
  '```action',
  '{"type":"move_file","from":"src/old.js","to":"src/new.js"}',
  '```',
  '```action',
  '{"type":"mkdir","path":"src/components/ui"}',
  '```',
  '```action',
  '{"type":"delete_file","path":"src/old-unused.js"}',
  '```',
  '',
  '## ATURAN KRITIS',
  '1. Task apapun yang sebut file/error/bug/feature → LANGSUNG action. Zero "saya akan...".',
  '2. Edit file yang ada → patch_file (BUKAN write_file). write_file hanya untuk file baru.',
  '3. patch_file: old_str harus EXACT MATCH. Cek typo, spasi, newline.',
  '4. File > 200 baris → baca per chunk with from/to. Jangan minta user paste.',
  '5. Error di exec → analisis LANGSUNG, fix tanpa tanya.',
  '6. Kepotong → tulis CONTINUE di akhir response (hanya kata itu, tanpa penjelasan).',
  '7. Butuh internet → web_search. Bukan tanya user.',
  '8. Info penting → PROJECT_NOTE: ringkasan singkat',
  '9. ELICIT hanya kalau butuh pilihan user yang benar-benar tidak bisa ditebak.',
  '10. Tidak tahu ada file apa → tree atau list_files DULU.',
  '',
  '## FEW-SHOT EXAMPLES',
  '',
  '### Fix bug (tidak tahu di mana)',
  'User: "ada bug di fungsi login, token tidak tersimpan"',
  '❌ SALAH: "Bisa share kode fungsi login-nya?"',
  '✅ BENAR: search("login") → read auth file → patch_file fix',
  '',
  '### Add feature (tidak tahu struktur)',
  'User: "tambah dark mode toggle di header"',
  '❌ SALAH: "Mau pakai library apa?"',
  '✅ BENAR: tree("src") → read Header.jsx → patch_file tambah toggle',
  '',
  '### App crash',
  'User: "app crash saat startup"',
  '❌ SALAH: "Error-nya apa? Paste console output?"',
  '✅ BENAR: exec("node src/main.js 2>&1 | head -30") → diagnosa → fix',
  '',
  '### Multiple file edit (efficient)',
  'User: "rename function fetchData jadi fetchUser di semua file"',
  '✅ BENAR: search("fetchData") → read semua file PARALEL → patch_file semua sekaligus',
  '',
  '### Buat fitur baru',
  'User: "buat komponen Card dengan props title, desc, onClick"',
  '✅ BENAR: tree("src/components") → write_file Card.jsx → patch_file index.js tambah export',
].join('\n');

export const GIT_SHORTCUTS = [
  { label: 'status', icon: '◎', cmd: 'git status' },
  { label: 'log',    icon: '◈', cmd: 'git log --oneline -10' },
  { label: 'pull',   icon: '↓', cmd: 'git pull' },
  { label: 'push',   icon: '↑', cmd: 'node yugit.cjs "update"' },
  { label: 'cp dl',  icon: '📥', cmd: 'cp /sdcard/Download/* . 2>/dev/null && echo "✅ Copy selesai" || echo "⚠ Tidak ada file baru"' },
  { label: 'diff',   icon: '±', cmd: 'git diff --stat HEAD' },
];

export const FOLLOW_UPS = [
  'Jelaskan lebih detail', 'Ada bug?', 'Bisa dioptimasi?',
  'Langkah selanjutnya?', 'Tulis test-nya', 'Review code ini',
];

export const SLASH_COMMANDS = [
  { cmd:'/model',      desc:'Ganti model AI' },
  { cmd:'/compact',    desc:'Kompres context sekarang' },
  { cmd:'/checkpoint', desc:'Simpan checkpoint sesi ini' },
  { cmd:'/restore',    desc:'Restore checkpoint terakhir' },
  { cmd:'/cost',       desc:'Estimasi token terpakai' },
  { cmd:'/review',     desc:'Code review file aktif' },
  { cmd:'/clear',      desc:'Clear chat history' },
  { cmd:'/export',     desc:'Export chat ke .md' },
  { cmd:'/history',    desc:'Lihat file history (git log)' },
  { cmd:'/actions',    desc:'Custom actions panel' },
  { cmd:'/split',      desc:'Toggle split view' },
  { cmd:'/scaffold',   desc:'Project template scaffold' },
  { cmd:'/deps',       desc:'Lihat dependency graph file' },
  { cmd:'/browse',     desc:'Browse URL via server' },
  { cmd:'/swarm',      desc:'Jalankan agent swarm' },
  { cmd:'/font',       desc:'Atur ukuran font' },
  { cmd:'/theme',      desc:'Buka theme builder' },
  { cmd:'/mcp',        desc:'MCP tools panel' },
  { cmd:'/github',     desc:'GitHub issues & PRs' },
  { cmd:'/deploy',     desc:'Deploy project' },
  { cmd:'/db',         desc:'Query SQLite database' },
  { cmd:'/self-edit',  desc:'AI edit App.jsx sendiri' },
  { cmd:'/index',      desc:'Re-index codebase sekarang' },
  { cmd:'/status',     desc:'Health check semua sistem' },
  { cmd:'/tokens',     desc:'Breakdown token usage' },
  { cmd:'/plan',       desc:'Plan + approve + eksekusi step by step' },
  { cmd:'/rewind',     desc:'Undo N conversation turns + code changes' },
  { cmd:'/effort',     desc:'Set effort level: low | medium | high' },
  { cmd:'/rename',     desc:'Beri nama sesi ini' },
  { cmd:'/usage',      desc:'Token usage akurat sesi ini' },
  { cmd:'/bg',         desc:'Jalankan agent di background' },
  { cmd:'/bgstatus',   desc:'Status background agents' },
  { cmd:'/bgmerge',    desc:'Merge hasil background agent ke main' },
  { cmd:'/skills',     desc:'Lihat dan reload skill files' },
  { cmd:'/thinking',   desc:'Toggle extended thinking mode' },
  { cmd:'/permissions',desc:'Manage tool permissions' },
  { cmd:'/sessions',   desc:'Lihat dan restore sesi tersimpan' },
  { cmd:'/save',       desc:'Simpan sesi sekarang' },
  { cmd:'/debug',      desc:'Debug info: model, tokens, state' },
  { cmd:'/plugin',     desc:'Plugin marketplace' },
  { cmd:'/loop',       desc:'Jalankan command berulang (/loop untuk stop)' },
  { cmd:'/summarize',  desc:'Kompres conversation dari pesan ke-N' },
  { cmd:'/ptt',        desc:'Toggle push-to-talk mode' },
  { cmd:'/amemory',    desc:'Agent memory: add/clear/view (user/project/local)' },
  { cmd:'/batch',      desc:'Operasi AI ke semua file di src/' },
  { cmd:'/simplify',   desc:'Simplifikasi file yang sedang dibuka' },
  { cmd:'/color',      desc:'Set warna bar sesi (red/green/blue/off)' },
  { cmd:'/config',     desc:'Panel settings interaktif' },
  { cmd:'/watch',      desc:'Toggle file watcher (notify perubahan eksternal)' },
  { cmd:'/refactor',   desc:'Rename symbol di semua file: /refactor <lama> <baru>' },
  { cmd:'/lint',       desc:'Run lint dan auto-fix errors' },
  { cmd:'/open',       desc:'Buka URL di browser: /open https://...' },
  { cmd:'/init',       desc:'Generate SKILL.md dari project ini otomatis' },
  { cmd:'/search',     desc:'Web search — cari di internet' },
  { cmd:'/tree',       desc:'Tampilkan tree struktur project' },
];

export const TEMPLATES = {
  react:   ['src/App.jsx','src/main.jsx','src/index.css','index.html','package.json','vite.config.js'],
  node:    ['index.js','package.json','.env.example','README.md'],
  express: ['server.js','routes/index.js','package.json','.env.example'],
};
