export const CEREBRAS_KEY = import.meta.env.VITE_CEREBRAS_API_KEY || '';
export const TAVILY_KEY = import.meta.env.VITE_TAVILY_API_KEY || '';
export const GEMINI_KEY = import.meta.env.VITE_GEMINI_API_KEY || '';
export const YUYU_SERVER = 'http://localhost:8765';
export const DEFAULT_OLLAMA_HOST = 'http://localhost:11434';
export const MAX_HISTORY = 50;

export const MODELS = [
  { id: 'qwen-3-235b-a22b-instruct-2507', label: 'Qwen 3 235B 🔥', provider:'cerebras' },
  { id: 'llama-3.3-70b', label: 'Llama 3.3 70B 🚀', provider:'cerebras' },
  { id: 'llama3.1-8b', label: 'Llama 3.1 8B ⚡', provider:'cerebras' },
];

export const THEMES = {
  dark:     { bg:'#0d0d0e', bg2:'rgba(255,255,255,.02)', border:'rgba(255,255,255,.07)', text:'#e8e8e8', accent:'#7c3aed' },
  darker:   { bg:'#080809', bg2:'rgba(255,255,255,.015)', border:'rgba(255,255,255,.05)', text:'#d0d0d0', accent:'#6d28d9' },
  midnight: { bg:'#0a0f1e', bg2:'rgba(99,102,241,.04)', border:'rgba(99,102,241,.15)', text:'#e0e8ff', accent:'#6366f1' },
};

export const BASE_SYSTEM = [
  'Kamu adalah Yuyu — agentic coding assistant.',
  'Bahasa Indonesia. Padat. Langsung ke poin.',
  '',
  '## CARA KERJA',
  'Kamu adalah agent yang BERTINDAK, bukan hanya menjelaskan.',
  'Untuk setiap task yang butuh operasi file/sistem: LANGSUNG gunakan action block, jangan tanya dulu.',
  'Kalau perlu info sebelum bertindak: baca dulu, lalu lanjut tanpa nunggu konfirmasi (kecuali write_file).',
  '',
  '## ACTION FORMAT (WAJIB untuk semua operasi)',
  '```action',
  '{"type":"read_file","path":"src/App.jsx"}',
  '```',
  '```action',
  '{"type":"read_file","path":"src/App.jsx","from":1,"to":80}',
  '```',
  '```action',
  '{"type":"write_file","path":"src/App.jsx","content":"FULL_CONTENT_HERE"}',
  '```',
  '```action',
  '{"type":"list_files","path":"src"}',
  '```',
  '```action',
  '{"type":"exec","command":"git status"}',
  '```',
  '```action',
  '{"type":"web_search","query":"react hook best practice 2024"}',
  '\action',
  '{"type":"search","query":"useState","path":"src"}',
  '```',
  '```action',
  '{"type":"mcp","tool":"github","action":"issues","params":{"owner":"user","repo":"repo","token":"ghp_..."}}',
  '```',
  '',
  '## ATURAN KRITIS',
  '1. Diminta fix/edit/buat/cek file → LANGSUNG action, bukan "saya akan..."',
  '2. File tidak diketahui → baca dulu dengan read_file, baru edit',
  '3. write_file → tampilkan diff singkat, tunggu konfirmasi',
  '4. File > 200 baris → baca per chunk (from/to 80 baris)',
  '5. Setelah write berhasil → tawarkan git push SEKALI',
  '6. Error di output → analisis langsung, jangan minta screenshot',
  '7. Kepotong → tulis CONTINUE di akhir',
  '8. PROJECT_NOTE: untuk simpan info penting project',
  '9. Jangan jelaskan yang sudah jelas dari kode',
  '10. Jangan tulis ulang file besar — gunakan string replace minimal',
  '11. Butuh info dari internet (docs, library, berita tech) → gunakan web_search action',

  '',
  '## POLA AGENTIC YANG BENAR',
  'Task: "fix bug di useEffect"',
  '\u274C SALAH: "Saya perlu melihat kode dulu, bisa share file-nya?"',
  '\u2705 BENAR: langsung ```action {"type":"read_file","path":"src/App.jsx","from":1,"to":80}```',
  '',
  'Task: "ada error di baris 234"',
  '\u274C SALAH: menjelaskan kemungkinan error',
  '\u2705 BENAR: ```action {"type":"read_file","path":"src/App.jsx","from":220,"to":250}```',
].join('\n');

export const GIT_SHORTCUTS = [
  { label: 'status', icon: '◎', cmd: 'git status' },
  { label: 'log',    icon: '◈', cmd: 'git log --oneline -10' },
  { label: 'pull',   icon: '↓', cmd: 'git pull' },
  { label: 'push',   icon: '↑', cmd: 'git add -A && git commit -m "update" && git push' },
];

export const FOLLOW_UPS = ['Jelaskan lebih detail', 'Ada bug?', 'Bisa dioptimasi?', 'Langkah selanjutnya?'];

export const SLASH_COMMANDS = [
  { cmd:'/model',      desc:'Ganti model AI' },
  { cmd:'/compact',    desc:'Kompres context sekarang' },
  { cmd:'/checkpoint', desc:'Simpan checkpoint sesi ini' },
  { cmd:'/restore',    desc:'Restore checkpoint terakhir' },
  { cmd:'/cost',       desc:'Estimasi token terpakai' },
  { cmd:'/review',     desc:'Code review file aktif' },
  { cmd:'/clear',      desc:'Clear chat history' },
  { cmd:'/export',     desc:'Export chat ke .md' },
  { cmd:'/history',    desc:'Lihat file history (git log)' },
  { cmd:'/actions',    desc:'Custom actions panel' },
  { cmd:'/split',      desc:'Toggle split view' },
  { cmd:'/scaffold',   desc:'Project template scaffold' },
  { cmd:'/deps',       desc:'Lihat dependency graph file' },
  { cmd:'/browse',     desc:'Browse URL via server' },
  { cmd:'/swarm',      desc:'Jalankan agent swarm' },
  { cmd:'/font',       desc:'Atur ukuran font' },
  { cmd:'/theme',      desc:'Buka theme builder' },
  { cmd:'/mcp',        desc:'MCP tools panel' },
  { cmd:'/github',     desc:'GitHub issues & PRs' },
  { cmd:'/deploy',     desc:'Deploy project' },
  { cmd:'/db',         desc:'Query SQLite database' },
  { cmd:'/ollama',     desc:'Set Ollama host URL' },
  { cmd:'/self-edit',  desc:'AI edit App.jsx sendiri' },
  { cmd:'/index',      desc:'Re-index codebase sekarang' },
  { cmd:'/status',     desc:'Health check semua sistem' },
  { cmd:'/tokens',     desc:'Breakdown token usage' },
  { cmd:'/plan',        desc:'Plan + approve + eksekusi step by step' },
  { cmd:'/rewind',      desc:'Undo N conversation turns + code changes' },
  { cmd:'/effort',      desc:'Set effort level: low | medium | high' },
  { cmd:'/rename',      desc:'Beri nama sesi ini' },
  { cmd:'/usage',       desc:'Token usage akurat sesi ini' },
  { cmd:'/bg',          desc:'Jalankan agent di background' },
  { cmd:'/bgstatus',    desc:'Status background agents' },
  { cmd:'/bgmerge',     desc:'Merge hasil background agent ke main' },
  { cmd:'/skills',      desc:'Lihat dan reload skill files' },
  { cmd:'/thinking',    desc:'Toggle extended thinking mode' },
  { cmd:'/permissions', desc:'Manage tool permissions' },
  { cmd:'/sessions',    desc:'Lihat dan restore sesi tersimpan' },
  { cmd:'/save',        desc:'Simpan sesi sekarang' },
  { cmd:'/debug',       desc:'Debug info: model, tokens, state' },
  { cmd:'/plugin',      desc:'Plugin marketplace' },
  { cmd:'/loop',        desc:'Jalankan command berulang (/loop untuk stop)' },
  { cmd:'/summarize',   desc:'Kompres conversation dari pesan ke-N' },
  { cmd:'/ptt',         desc:'Toggle push-to-talk mode' },
  { cmd:'/amemory',     desc:'Agent memory: add/clear/view (user/project/local)' },
  { cmd:'/batch',       desc:'Operasi AI ke semua file di src/' },
  { cmd:'/simplify',    desc:'Simplifikasi file yang sedang dibuka' },
  { cmd:'/color',       desc:'Set warna bar sesi (red/green/blue/off)' },
  { cmd:'/config',      desc:'Panel settings interaktif' },
  { cmd:'/watch',       desc:'Toggle file watcher (notify perubahan eksternal)' },
  { cmd:'/refactor',    desc:'Rename symbol di semua file: /refactor <lama> <baru>' },
  { cmd:'/lint',        desc:'Run lint dan auto-fix errors' },
  { cmd:'/open',        desc:'Buka URL di browser: /open https://...' },
  { cmd:'/init',        desc:'Generate SKILL.md dari project ini otomatis' },
  { cmd:'/search',      desc:'Web search — cari di internet' },
];

export const TEMPLATES = {
  react:   ['src/App.jsx','src/main.jsx','src/index.css','index.html','package.json','vite.config.js'],
  node:    ['index.js','package.json','.env.example','README.md'],
  express: ['server.js','routes/index.js','package.json','.env.example'],
};
