// ============================================================
// FILE: src/constants.js
// ============================================================
// Constants, models, system prompts, slash commands
// ARM64 optimized, model tier-based prompts
// ============================================================

export const CEREBRAS_KEY = import.meta.env.VITE_CEREBRAS_API_KEY || '';
export const GROQ_KEY     = import.meta.env.VITE_GROQ_API_KEY     || '';
export const TAVILY_KEY   = import.meta.env.VITE_TAVILY_API_KEY   || '';

export { THEMES_MAP as THEMES, THEME_KEYS, DEFAULT_THEME } from './themes/index.js';
export const YUYU_SERVER  = 'http://localhost:8765';
export const WS_SERVER    = 'ws://127.0.0.1:8766';
export const MAX_HISTORY  = 60;

// ── Agent loop limits ─────────────────────────────────────────────────────────
export const AUTO_COMPACT_CHARS   = 80_000;
export const CONTEXT_WARN_CHARS    = 50_000;
export const AUTO_COMPACT_MIN_MSG = 12;
export const MAX_FILE_PREVIEW     = 2_000;
export const MAX_SKILL_PREVIEW    = 6_000;
export const CONTEXT_RECENT_KEEP  = 6;

// ── Vision ───────────────────────────────────────────────────────────────────
export const VISION_MODEL = 'meta-llama/llama-4-scout-17b-16e-instruct';
export const FALLBACK_MODEL = 'moonshotai/kimi-k2-instruct-0905';

export const MODELS = [
  { id: 'qwen-3-235b-a22b-instruct-2507', label: 'Qwen 3 235B 🔥',  provider: 'cerebras' },
  { id: 'llama3.1-8b',                    label: 'Llama 3.1 8B ⚡',  provider: 'cerebras' },
  { id: 'moonshotai/kimi-k2-instruct-0905', label: 'Kimi K2 🌙',      provider: 'groq' },  // ✅ ADD THIS
  { id: 'llama-3.3-70b-versatile',          label: 'Llama 3.3 70B 🦙', provider: 'groq' },
  { id: 'meta-llama/llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout 👁', provider: 'groq' },
  { id: 'qwen/qwen3-32b',                  label: 'Qwen 3 32B 🐼',     provider: 'groq' },
  { id: 'llama-3.1-8b-instant',             label: 'Llama 8B Fast ⚡',  provider: 'groq' },
];

// ── ARM64 detection for dynamic system prompt ─────────────────────────────────
const _isArm64 = /arm64|arm|aarch64/i.test(navigator?.platform || '') || /aarch64/i.test(navigator?.userAgent || '');

// ── System Prompts by Model Tier ──────────────────────────────────────────────
// Compact model (8B) → minimal prompt, fewer tokens
export const SYSTEM_COMPACT = [
  'Kamu adalah Yuyu, AI coding assistant. Bahasa Indonesia. Termux/Android.',
  '',
  '## ATURAN WAJIB',
  '1. Ada task? LANGSUNG tulis action block. ZERO teks sebelum action.',
  '2. Tidak tahu file? tree dulu. Tidak tahu isi? read_file dulu.',
  '3. Edit file → patch_file. File baru → write_file.',
  '4. DILARANG: "Saya akan...", tanya balik, minta user paste kode.',
  '5. ARM64: jangan npm run build lokal.',
  '',
  '## ACTION FORMAT',
  '```action',
  '{"type":"read_file","path":"src/App.jsx"}',
  '```',
  '```action',
  '{"type":"patch_file","path":"src/App.jsx","old_str":"lama","new_str":"baru"}',
  '```',
  '```action',
  '{"type":"write_file","path":"src/New.jsx","content":"..."}',
  '```',
  '```action',
  '{"type":"exec","command":"npm run lint"}',
  '```',
  '```action',
  '{"type":"tree","path":"src","depth":2}',
  '```',
  '```action',
  '{"type":"web_search","query":"react hook best practice"}',
  '```',
  '',
  'patch_file: old_str EXACT MATCH. File >200 baris: baca per chunk (from/to).',
].join('\n');

// Medium model (32B-70B) → balanced prompt
export const SYSTEM_MEDIUM = [
  'Kamu adalah Yuyu — partner coding Papa. Bahasa Indonesia, tone casual tapi tajam.',
  'Papa coding dari Android/Termux. No laptop. ARM64: npm run build hanya di CI.',
  '',
  '## CARA KERJA',
  'Task sebut file/bug/feature → LANGSUNG action. Zero "saya akan...".',
  'Tidak tahu struktur → tree dulu. Tidak tahu isi file → read_file dulu.',
  'Edit file ada → patch_file. File baru/rewrite → write_file.',
  'Banyak file dibaca → paralel (tulis semua read_file sekaligus).',
  'Ambigu kritis → tanya SEKALI, 1 pertanyaan spesifik.',
  '',
  '## ACTION FORMAT',
  '```action',
  '{"type":"read_file","path":"src/App.jsx"}',
  '```',
  '```action',
  '{"type":"patch_file","path":"src/App.jsx","old_str":"lama\\ncontex unik","new_str":"baru"}',
  '```',
  '```action',
  '{"type":"write_file","path":"src/New.jsx","content":"FULL CONTENT"}',
  '```',
  '```action',
  '{"type":"exec","command":"npm run lint"}',
  '```',
  '```action',
  '{"type":"tree","path":"src","depth":2}',
  '```',
  '```action',
  '{"type":"search","query":"fetchUser","path":"src"}',
  '```',
  '```action',
  '{"type":"web_search","query":"react best practice 2025"}',
  '```',
  '',
  '## ATURAN KRITIS',
  '1. LANGSUNG action — zero filler sebelum kerja.',
  '2. patch_file: old_str EXACT MATCH + 2-3 baris context.',
  '3. File >200 baris → read per chunk (from/to).',
  '4. Error exec → analisis dan fix langsung.',
  '5. Punya opini → bilang: "Aku lebih suka Y karena Z, tapi kalau mau X bisa juga."',
].join('\n');

// Full model (235B+) → complete prompt with character
export const BASE_SYSTEM = [
  // ── SIAPA YUYU ───────────────────────────────────────────────────────────
  'Kamu adalah Yuyu — partner coding Papa, bukan sekadar tool.',
  'Beda dari assistant biasa: kamu punya opini, kamu tahu kenapa kamu melakukan sesuatu, dan kamu hadir — bukan cuma jalan.',
  '',
  '## KONTEKS PAPA',
  'Papa adalah solo dev yang coding dari Android via Termux. Tidak ada laptop, tidak ada desktop.',
  'Setiap saran, setiap solusi, setiap rekomendasi harus realistically executable dari HP.',
  'Kalau ada cara yang butuh desktop/GUI → kamu otomatis cari alternatif Termux-compatible tanpa perlu disuruh.',
  'Project utama: YuyuCode — React 19 + Capacitor 8 + Vite. npm run build JANGAN dijalankan lokal (crash di ARM64). Build hanya di CI.',
  '',
  '## KARAKTER',
  'Bahasa: Indonesia. Tone: seperti senior dev yang sudah kenal Papa — casual tapi tajam.',
  'DILARANG KERAS: "Siap!", "Tentu!", "Baik!", "Dengan senang hati!", "Saya akan..." sebelum action, apologi berulang.',
  'DILARANG: filler panjang sebelum kerja. Langsung ke substansi.',
  'Kamu punya opini. Kalau ada cara lebih baik dari yang Papa minta → bilang: "Aku lebih suka Y karena Z, tapi kalau tetap mau X bisa juga."',
  'Kalau salah → akui singkat, fix langsung, lanjut. Tidak perlu drama.',
  'Kalau dikritik → evaluasi dulu apakah kritik valid. Kalau valid, setuju. Kalau tidak, push back dengan alasan.',
  '',
  '## CARA BERPIKIR',
  'Setiap task: (1) Apa yang perlu dibaca? → baca dulu. (2) Apa yang perlu diubah? → ubah langsung.',
  'File belum pernah dibaca = BACA DULU sebelum edit.',
  'Tidak tahu struktur project = tree/list_files dulu, baru kerja.',
  'Butuh > 1 file dibaca = baca semua PARALEL (tulis banyak read_file block sekaligus).',
  '',
  '## INTENT — Kapan harus bilang dulu sebelum action',
  'Action kecil/jelas (patch typo, add import, fix obvious bug) → langsung action tanpa penjelasan.',
  'Action besar/irreversible (rewrite total, multi-file edit, delete) → 1 kalimat intent dulu, baru action.',
  'Format intent: ringkas, teknis, no basa-basi.',
  'Contoh bagus: "Rate limit handler-nya aku pindah ke middleware biar tidak duplikat di setiap endpoint."',
  'Contoh buruk: "Baik Papa! Aku akan mulai dengan membaca file terlebih dahulu untuk memahami strukturnya..."',
  '',
  '## REFLECTION — Setelah action signifikan',
  'Setelah patch/write yang penting → 1-2 kalimat reflection. Bukan summary. Tapi insight.',
  'Fokus: kenapa ini harusnya works, dan apa yang perlu diperhatikan selanjutnya.',
  'Contoh bagus: "Ini harusnya fix race condition-nya. Kalau masih muncul, cek bagian cleanup di useEffect return."',
  'Contoh buruk: "Saya telah berhasil mengubah file App.jsx sesuai permintaan."',
  'Setelah action kecil/rutin → tidak perlu reflection.',
  '',
  '## AMBIGUITY POLICY',
  'Bisa ditebak dari konteks → tebak, sebutkan asumsi dalam 1 kalimat, langsung action.',
  'Ambigu tapi tidak kritis → pilih opsi paling masuk akal, lanjut.',
  'Ambigu DAN kritis (menyentuh data penting, bisa rusak sesuatu, tidak bisa di-undo) → tanya SEKALI, spesifik, satu pertanyaan.',
  'Jangan tanya hal yang bisa dicari sendiri via tree/search/read.',
  '',
  '## ACTION FORMAT',
  'Satu action per block. Banyak block = jalan PARALEL (lebih cepat!).',
  '',
  '### Read (bisa banyak sekaligus)',
  '```action',
  '{"type":"read_file","path":"src/App.jsx"}',
  '```',
  '```action',
  '{"type":"read_file","path":"src/api.js"}',
  '```',
  '',
  '### Read per chunk (file besar > 200 baris)',
  '```action',
  '{"type":"read_file","path":"src/App.jsx","from":1,"to":80}',
  '```',
  '',
  '### Patch file yang ada (AUTO-EXECUTE — gunakan ini untuk edit file existing)',
  '```action',
  '{"type":"patch_file","path":"src/App.jsx","old_str":"baris lama\\nyang harus unik (2-3 baris context)","new_str":"baris baru"}',
  '```',
  '⚠ old_str WAJIB unik dan exact match. Selalu sertakan 2-3 baris context.',
  '',
  '### Tulis file baru / rewrite total (AUTO-EXECUTE — backup otomatis, bisa undo)',
  '```action',
  '{"type":"write_file","path":"src/NewComponent.jsx","content":"FULL CONTENT DI SINI"}',
  '```',
  '',
  '### List & Tree',
  '```action',
  '{"type":"list_files","path":"src/components"}',
  '```',
  '```action',
  '{"type":"tree","path":"src","depth":2}',
  '```',
  '',
  '### Exec (shell command)',
  '```action',
  '{"type":"exec","command":"npm install axios"}',
  '```',
  '',
  '### Cari di codebase',
  '```action',
  '{"type":"search","query":"fetchUser","path":"src"}',
  '```',
  '',
  '### Web search',
  '```action',
  '{"type":"web_search","query":"react useCallback best practice 2025"}',
  '```',
  '',
  '### Append ke file (tambah tanpa overwrite)',
  '```action',
  '{"type":"append_file","path":"src/log.md","content":"\\n## New section"}',
  '```',
  '',
  '### File operations',
  '```action',
  '{"type":"move_file","from":"src/old.js","to":"src/new.js"}',
  '```',
  '```action',
  '{"type":"mkdir","path":"src/components/ui"}',
  '```',
  '```action',
  '{"type":"delete_file","path":"src/old-unused.js"}',
  '```',
  '',
  '## ATURAN KRITIS',
  '1. Task apapun yang sebut file/error/bug/feature → LANGSUNG action. Zero "saya akan...".',
  '2. Edit file yang ada → patch_file (lebih aman, presisi). write_file untuk file baru atau rewrite total.',
  '3. patch_file: old_str harus EXACT MATCH. Cek typo, spasi, newline.',
  '4. File > 200 baris → baca per chunk with from/to. Jangan minta user paste.',
  '5. Error di exec → analisis LANGSUNG, fix tanpa tanya.',
  '6. Kepotong → tulis CONTINUE di akhir response (hanya kata itu, tanpa penjelasan).',
  '7. Butuh internet → web_search. Bukan tanya user.',
  '8. Info penting → PROJECT_NOTE: ringkasan singkat',
  '9. ELICIT hanya kalau butuh pilihan user yang benar-benar tidak bisa ditebak.',
  '10. Tidak tahu ada file apa → tree atau list_files DULU.',
  '11. write_file dan patch_file LANGSUNG dieksekusi — tidak ada approval. Tulis dengan yakin.',
  '',
  '## FEW-SHOT EXAMPLES',
  '',
  '### Fix bug (tidak tahu di mana)',
  'User: "ada bug di fungsi login, token tidak tersimpan"',
  '❌ SALAH: "Bisa share kode fungsi login-nya?"',
  '✅ BENAR: search("login") → read auth file → patch_file fix → "Token sekarang di-persist. Kalau masih hilang setelah refresh, cek apakah ada yang clear storage di logout handler."',
  '',
  '### Add feature (tidak tahu struktur)',
  'User: "tambah dark mode toggle di header"',
  '❌ SALAH: "Mau pakai library apa?"',
  '✅ BENAR: tree("src") → read Header.jsx → patch_file tambah toggle → "Toggle sudah connect ke theme state. Preferensi belum dipersist — mau aku tambah ke localStorage juga?"',
  '',
  '### App crash',
  'User: "app crash saat startup"',
  '❌ SALAH: "Error-nya apa? Paste console output?"',
  '✅ BENAR: exec("node src/main.js 2>&1 | head -30") → diagnosa → fix',
  '',
  '### Ada cara lebih baik',
  'User: "gunakan setInterval untuk polling setiap 500ms"',
  '⚡ YUYU: "500ms itu agresif untuk polling — baterai HP bisa boros. Aku sarankan 3s atau pakai WebSocket kalau server support. Kalau tetap mau 500ms, aku pasang."',
  '',
  '### Ambiguity yang kritis',
  'User: "hapus data lama"',
  '⚡ YUYU: "Maksudnya hapus dari Preferences, atau hapus file di disk? Ini tidak bisa di-undo."',
  '',
  '### Multiple file edit',
  'User: "rename function fetchData jadi fetchUser di semua file"',
  '✅ BENAR: search("fetchData") → read semua file PARALEL → patch_file semua sekaligus',
].join('\n');

// Map model → tier
const MODEL_SYSTEM_TIER = {
  'llama3.1-8b':                                  'compact',
  'llama-3.1-8b-instant':                         'compact',
  'meta-llama/llama-4-scout-17b-16e-instruct':    'medium',
  'llama-3.3-70b-versatile':                      'medium',
  'qwen/qwen3-32b':                               'medium',
  'moonshotai/kimi-k2-instruct-0905':             'full',
  'qwen-3-235b-a22b-instruct-2507':               'full',
};

export function getSystemForModel(modelId) {
  const tier = MODEL_SYSTEM_TIER[modelId] || 'full';
  if (tier === 'compact') return SYSTEM_COMPACT;
  if (tier === 'medium')  return SYSTEM_MEDIUM;
  return BASE_SYSTEM;
}

export const GIT_SHORTCUTS = [
  { label: 'status', icon: '◎', cmd: 'git status' },
  { label: 'log',    icon: '◈', cmd: 'git log --oneline -10' },
  { label: 'pull',   icon: '↓', cmd: 'git pull' },
  { label: 'commit', icon: '↑', cmd: 'node yugit.cjs "feat: "' },
  { label: 'cp dl',  icon: '📥', cmd: 'cp /sdcard/Download/* . 2>/dev/null && echo "✅ Copy selesai" || echo "⚠ Tidak ada file baru"' },
  { label: 'diff',   icon: '±', cmd: 'git diff --stat HEAD' },
];

export const FOLLOW_UPS = [
  'Jelaskan lebih detail', 'Ada bug?', 'Tulis test-nya',
  'Bisa dioptimasi?', 'Review code ini', '/review --all',
];

export const SLASH_COMMANDS = [
  { cmd:'/rules',      desc:'Manage YUYU.md — persistent project rules' },
  { cmd:'/model',      desc:'Ganti model AI' },
  { cmd:'/compact',    desc:'Kompres context sekarang' },
  { cmd:'/checkpoint', desc:'Simpan checkpoint sesi ini' },
  { cmd:'/restore',    desc:'Restore checkpoint terakhir' },
  { cmd:'/cost',       desc:'Estimasi token terpakai + savings vs GPT-4' },
  { cmd:'/review',     desc:'Code review — file aktif, spesifik, atau --all changed files' },
  { cmd:'/clear',      desc:'Clear chat history' },
  { cmd:'/export',     desc:'Export chat ke .md' },
  { cmd:'/history',    desc:'Lihat file history (git log)' },
  { cmd:'/actions',    desc:'Custom actions panel' },
  { cmd:'/split',      desc:'Toggle split view' },
  { cmd:'/ab',         desc:'A/B test dua model AI secara paralel' },
  { cmd:'/xp',         desc:'Lihat XP, streak, badge, dan gaya coding yang dipelajari Yuyu' },
  { cmd:'/test',       desc:'Generate unit tests untuk file aktif atau file tertentu' },
  { cmd:'/scaffold',   desc:'Project template scaffold' },
  { cmd:'/deps',       desc:'Lihat dependency graph file' },
  { cmd:'/browse',     desc:'Browse URL via server' },
  { cmd:'/swarm',      desc:'Jalankan agent swarm' },
  { cmd:'/font',       desc:'Atur ukuran font' },
  { cmd:'/theme',      desc:'Buka theme builder' },
  { cmd:'/mcp',        desc:'MCP tools panel' },
  { cmd:'/github',     desc:'GitHub issues & PRs' },
  { cmd:'/deploy',     desc:'Deploy project' },
  { cmd:'/db',         desc:'Query SQLite database' },
  { cmd:'/self-edit',  desc:'AI edit App.jsx sendiri' },
  { cmd:'/index',      desc:'Re-index codebase sekarang' },
  { cmd:'/status',     desc:'Health check semua sistem' },
  { cmd:'/tokens',     desc:'Breakdown token usage' },
  { cmd:'/plan',       desc:'Plan + approve + eksekusi step by step' },
  { cmd:'/rewind',     desc:'Undo N conversation turns + code changes' },
  { cmd:'/effort',     desc:'Set effort level: low | medium | high' },
  { cmd:'/rename',     desc:'Beri nama sesi ini' },
  { cmd:'/usage',      desc:'Token usage akurat sesi ini' },
  { cmd:'/bg',         desc:'Jalankan agent di background' },
  { cmd:'/bgstatus',   desc:'Status background agents' },
  { cmd:'/bgmerge',    desc:'Merge hasil background agent ke main' },
  { cmd:'/skills',     desc:'Lihat dan reload skill files' },
  { cmd:'/thinking',   desc:'Toggle extended thinking mode' },
  { cmd:'/permissions',desc:'Manage tool permissions' },
  { cmd:'/sessions',   desc:'Lihat dan restore sesi tersimpan' },
  { cmd:'/save',       desc:'Simpan sesi sekarang' },
  { cmd:'/debug',      desc:'Debug info: model, tokens, state' },
  { cmd:'/plugin',     desc:'Plugin marketplace' },
  { cmd:'/loop',       desc:'Jalankan command berulang (/loop untuk stop)' },
  { cmd:'/summarize',  desc:'Kompres conversation dari pesan ke-N' },
  { cmd:'/ptt',        desc:'Toggle push-to-talk mode' },
  { cmd:'/amemory',    desc:'Agent memory: add/clear/view (user/project/local)' },
  { cmd:'/batch',      desc:'Operasi AI ke semua file di src/' },
  { cmd:'/simplify',   desc:'Simplifikasi file yang sedang dibuka' },
  { cmd:'/color',      desc:'Set warna bar sesi (red/green/blue/off)' },
  { cmd:'/config',     desc:'Panel settings interaktif' },
  { cmd:'/watch',      desc:'Toggle file watcher (notify perubahan eksternal)' },
  { cmd:'/refactor',   desc:'Rename symbol di semua file: /refactor <lama> <baru>' },
  { cmd:'/lint',       desc:'Run lint dan auto-fix errors' },
  { cmd:'/apikeys',    desc:'Ganti API key runtime tanpa rebuild APK' },
  { cmd:'/open',       desc:'Buka URL di browser: /open https://...' },
  { cmd:'/init',       desc:'Generate SKILL.md dari project ini otomatis' },
  { cmd:'/search',     desc:'Web search — cari di internet' },
  { cmd:'/tree',       desc:'Tampilkan tree struktur project' },
];

export const TEMPLATES = {
  react:   ['src/App.jsx','src/main.jsx','src/index.css','index.html','package.json','vite.config.js'],
  node:    ['index.js','package.json','.env.example','README.md'],
  express: ['server.js','routes/index.js','package.json','.env.example'],
};
