// llms.cjs
const fs = require('fs');
const path = require('path');

function generateLlmsTxt(fileData, root = process.cwd()) {
  const pkg = (() => {
    try { return JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')); } catch { return {}; }
  })();

  const hotFiles = Object.entries(fileData)
    .filter(([,d]) => d.salience > 15)
    .sort(([,a],[,b]) => b.salience - a.salience)
    .slice(0, 10)
    .map(([rel, d]) => `- \`${rel}\` — ${d.syms.slice(0,3).map(s=>s.name).join(', ')}${d.syms.length > 3 ? ` +${d.syms.length-3} more` : ''}`);

  const hooks = Object.entries(fileData)
    .filter(([rel]) => rel.includes('hooks/'))
    .map(([rel, d]) => `- \`${rel}\` — ${d.syms.map(s=>s.name).join(', ')}`)
    .join('\n');

  const components = Object.entries(fileData)
    .filter(([rel]) => rel.includes('components/'))
    .map(([rel, d]) => `- \`${rel}\` (${d.lines}L)`)
    .join('\n');

  return `# YuyuCode — LLM Context Brief
> Version: ${pkg.version || 'unknown'} | Generated: ${new Date().toISOString().split('T')[0]}

## What is this project?
YuyuCode is a Claude Code / Cursor-style agentic coding assistant built natively for Android.
Runs entirely on a phone (Oppo A77s, Snapdragon 680) via Termux. No laptop. No desktop.

## Architecture overview
- **Frontend**: React 19 + Vite 5, runs as Capacitor Android app
- **Backend**: \`yuyu-server.js\` — local Node.js server in Termux (HTTP :8765, WS :8766)
- **Editor**: CodeMirror 6 with full extension suite (vim, emmet, ghost text, LSP, blame, collab)
- **AI**: Cerebras (default, Qwen 3 235B) → Groq (fallback, Kimi K2 262K)
- **Build**: GitHub Actions → signed APK

## Critical constraints — NEVER change without understanding why
- \`"overrides": { "rollup": "npm:@rollup/wasm-node" }\` — required for ARM64 Termux build
- \`vitest@3\` — v4 crashes silently on Termux ARM64 (Illegal instruction)
- Never override \`global.TextDecoder\` in tests — infinite recursion on Node 24
- \`android/\` folder — Capacitor-managed, manual edits break sync

## Hot files (highest salience)
${hotFiles.join('\n')}

## Hooks
${hooks}

## Components
${components}

## Agent loop flow
1. User sends message → \`useAgentLoop.sendMsg()\`
2. Auto-compact if context > 80K chars
3. \`gatherProjectContext()\` — reads handoff → map → llms.txt → tree → keyword files
4. \`buildSystemPrompt()\` — injects memories, skills, file context, handoff
5. Stream to AI → parse \`<action>\` blocks
6. Execute actions (parallel: read/search/list; serial: exec/mcp)
7. Feed results back → loop until done

## Key patterns
- All AI calls via \`askCerebrasStream()\` in \`src/api.js\`
- Server actions via \`callServer({type, ...})\` — see \`yuyu-server.js\`
- Slash commands in \`useSlashCommands.js\` (~60 commands)
- /compact is deprecated — use /handoff instead
- Theme tokens: never hardcode colors — use \`T.colorName\` from active theme
- Tests: \`npx vitest run\` must pass 1235/1235. \`npm run lint\` must be 0 errors.

## Context quantization files (auto-loaded by gatherProjectContext)
- \`.yuyu/handoff.md\` — session handoff (run /handoff to update)
- \`.yuyu/map.md\` — symbol index with salience scores
- \`.yuyu/compressed.md\` — repomix-style compressed source (~70% reduction)
- \`llms.txt\` — this file

## yuyu-server index endpoint
\`\`\`js
// Real-time symbol extraction — no file needed
callServer({ type: 'index', path: '/path/to/src' })
// Returns: markdown of all function signatures, no bodies
\`\`\`

## Run map generator
\`\`\`bash
node yuyu-map.cjs           # full regeneration
node yuyu-map.cjs --compress-only  # only update compressed.md
\`\`\`

> Auto-generated by \`node yuyu-map.cjs\` — run after major refactors
`;
}

module.exports = { generateLlmsTxt };
